Remove words/dicts before the website is built. forrest tried to validate .xml documents that don't belong to the website, but failed.

diff --git a/divvun2web b/divvun2web
--- a/divvun2web
+++ b/divvun2web
@@ -67,21 +67,16 @@ build_and_copy_sites()
 
 	# Build the site, at the same time checking the docs
 	forrest clean
+	rm -rf ../../words/dicts
 	forrest -Dforrest.jvmargs=-Djava.awt.headless=true validate-xdocs
 	if [ "$?"  == "0" ]
 	then
 		nice -n 10 forrest -Dforrest.jvmargs=-Djava.awt.headless=true
-		if [ "$?"  == "0" ]
-		then
-			cd build/site
-			scp -rq * $SITE@giellatekno.uit.no:public_html/.
-		else
-			echo "Build failed ..."
-			exit 1
-		fi
-		
+		cd build/site
+		scp -r  * gtuit@giellatekno.uit.no:public_html/.
 	else
-		exit 1
+	    echo "Build failed ..."
+	    exit 1
 	fi
 }
 
